# -*- coding: utf-8 -*-
"""LA_Project_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PTcwQXD9FIwJFnQGWOtVnVv5BS8hXjXo

# Linear Algebra Project 01: Degrees of Separation
## Math 120(H)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from IPython.display import display

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 50)
pd.set_option('display.width', 200)
np.set_printoptions(linewidth=300, threshold=10000)

"""According to the project definition, the adjacency matrix requires:
row = who follows person, and
the coulmn = whom person follows.
"""

raw_df = pd.read_csv('data.csv', index_col=0)
raw_df.columns = raw_df.index
A_raw = raw_df.values.astype(int)

A = A_raw.T
names = list(raw_df.index)
n = len(names)

print(f"Number of students (n): {n}")
print(f"Matrix shape: {A.shape}")
print(f"Total follow relationships: {A.sum()}")

print("Student Index Mapping:")
print("-" * 50)
for idx, name in enumerate(names, start=1):
    print(f"  {idx:>2}. {name}")

index_labels = [str(i) for i in range(1, n+1)]
A_df = pd.DataFrame(A, index=index_labels, columns=index_labels)

print("Adjacency Matrix A  (a_ij = 1 means person j follows person i)")
print("Rows = person being followed, Columns = person who follows")
print()
display(A_df)

"""# Heatmap Visualization"""

fig, ax = plt.subplots(figsize=(12, 10))
im = ax.imshow(A, cmap='Blues', aspect='auto')
ax.set_title('Adjacency Matrix A — Instagram Follow Network', fontsize=14, pad=15)
ax.set_xlabel('Person j (follower)', fontsize=11)
ax.set_ylabel('Person i (followed)', fontsize=11)
ax.set_xticks(range(n))
ax.set_yticks(range(n))
ax.set_xticklabels(index_labels, fontsize=6)
ax.set_yticklabels(index_labels, fontsize=6)
plt.colorbar(im, ax=ax, label='1 = follows, 0 = does not follow')
plt.tight_layout()
plt.savefig('matrix_A_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print("Heatmap saved as 'matrix_A_heatmap.png'")

"""## Task 2: Analysis of A²

### Computing A²
"""

A2 = A @ A

A2_df = pd.DataFrame(A2, index=index_labels, columns=index_labels)
print("A² = A × A")
print(f"Shape: {A2.shape}")
print()
display(A2_df)

"""### 2(c) — Zero entries in A²

A zero at $(A^2)_{ij} = 0$ shows **there is no person $k$ in the class such that $j$ follows $k$ and $k$ follows $i$** — i.e., there is no directed path of length 2 from person $j$ to person $i$ through any intermediate classmate.
"""

zeros_A2 = [(i+1, j+1, names[i], names[j])
            for i in range(n) for j in range(n)
            if A2[i, j] == 0]

print(f"Total zero entries in A²: {len(zeros_A2)}")
print(f"Off-diagonal zeros: {sum(1 for z in zeros_A2 if z[0] != z[1])}")
print("Interpretation of zero entries:")
print("  (A²)_ij = 0 No classmate k exists such that j→k→i")
print()
print("Notable cases (first 10 off-diagonal zeros):")
count = 0
for (i, j, ni, nj) in zeros_A2:
    if i != j:
        print(f"  ({i:>2},{j:>2}) — No 2-step path from {nj} to {ni}")
        count += 1
        if count >= 10:
            break

print("Checking for students with no connections:")
for idx, name in enumerate(names):
    out_degree = A[:, idx].sum()
    in_degree  = A[idx, :].sum()
    if out_degree == 0 or in_degree == 0:
        print(f"  {name}: in-degree={in_degree}, out-degree={out_degree}")

"""### 2(d) — Maximum entry in A²

$(A^2)_{ij} = \sum_{k=1}^{n} a_{ik} \cdot a_{kj}$. Since each term is 0 or 1, the maximum value is $n$ (all $n$ possible intermediaries exist). This would require person $j$ to follow **everyone**, and **everyone** to follow person $i$.

With $n = 45$ students (and $a_{ii} = 0$), the theoretical maximum is **44**.

**Network structure for maximum:** Person $j$ follows all other 44 other classmates, and all 44 other classmates follow person $i$.
"""

max_val = A2.max()
max_pos = np.unravel_index(A2.argmax(), A2.shape)
i_max, j_max = max_pos

print(f"Theoretical maximum for A² entry: {n - 1}")
print(f"Observed maximum in our A²:        {max_val}")
print(f"Achieved at: ({i_max+1}, {j_max+1})")
print(f"  i = {names[i_max]}")
print(f"  j = {names[j_max]}")
print()
print(f"Meaning: There are {max_val} distinct 2-step paths from {names[j_max]} to {names[i_max]},")
print(f"i.e., {max_val} classmates that {names[j_max]} follows who also follow {names[i_max]}.")

"""---
## Task 3: Higher Powers and Connectivity

### Computing successive Powers Until all positive Matrix
"""

powers = {1: A, 2: A2}
Ak = A2.copy()
found_all_positive = False
m = None

print("Tracking zero entries across matrix powers:")
print(f"  A^1 : {np.sum(A  == 0):>5} zeros, max = {A.max():>6}")
print(f"  A^2 : {np.sum(A2 == 0):>5} zeros, max = {A2.max():>6}")

for k in range(3, 21):
    Ak = Ak @ A
    powers[k] = Ak.copy()
    z = np.sum(Ak == 0)
    print(f"  A^{k:<2}: {z:>5} zeros, max = {Ak.max():>10,}")
    if z == 0 and not found_all_positive:
        found_all_positive = True
        m = k
        print(f"  *** All entries positive at k = {k} ***")
        break

if not found_all_positive:
    print()
    print(">>> Some zeros persist — the graph is NOT strongly connected.")

"""### 3(b) and (c) — Interpretation of Persistent Zeros

Since the zero count does not reach zero, **there is no integer $m$ such that all entries of $A^m$ are positive**. This means our network is **not strongly connected**.
"""

# using A^10
A10 = powers[10] if 10 in powers else None
if A10 is None:
    Ak = A.copy()
    for _ in range(9):
        Ak = Ak @ A
    A10 = Ak

persistent_zeros = [(i, j) for i in range(n) for j in range(n) if A10[i,j] == 0 and i != j]

print(f"Persistent zero off-diagonal pairs: {len(persistent_zeros)}")
print()
print("These zeros mean: no directed walk of ANY length exists from j to i.")
print("This implies the graph is NOT strongly connected.")
print("Structurally isolated students (cause of disconnection):")
for idx, name in enumerate(names):
    out_deg = A[:, idx].sum()  # how many people person idx follows
    in_deg  = A[idx, :].sum()  # how many people follow person idx
    if out_deg == 0:
        print(f"  SOURCE-SINK (no out-edges): {name} — follows nobody and nobody follows back")
    elif in_deg == 0:
        print(f"  SINK (no in-edges): {name}")
    elif out_deg == 0:
        print(f"  SOURCE (no out-edges): {name}")

"""### Visualization of how zeros decrese."""

power_keys = sorted(powers.keys())
zero_counts = [np.sum(powers[k] == 0) for k in power_keys]

plt.figure(figsize=(9, 4))
plt.plot(power_keys, zero_counts, 'o-', color='steelblue', linewidth=2, markersize=7)
plt.xlabel('Power k', fontsize=12)
plt.ylabel('Number of zero entries', fontsize=12)
plt.title('Zero Entries in Aᵏ vs. Power k', fontsize=13)
plt.xticks(power_keys)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('zero_counts.png', dpi=150, bbox_inches='tight')
plt.show()

"""### 3(d): Since some entries in A^m never become nonzero.
Instead, we are going to identify pairs which become nonzero at the last.
And those which remain zero always.
"""

first_nonzero = np.full((n, n), np.inf)

for k in sorted(powers.keys()):
    Pk = powers[k]
    for i in range(n):
        for j in range(n):
            if Pk[i,j] > 0 and first_nonzero[i,j] == np.inf:
                first_nonzero[i,j] = k
finite_mask = np.isfinite(first_nonzero) & (np.eye(n) == 0)
max_k = first_nonzero[finite_mask].max()
late_pairs = [(i, j) for i in range(n) for j in range(n)
              if first_nonzero[i,j] == max_k and i != j]

print(f"Latest power at which any new entry first becomes nonzero: k = {int(max_k)}")
print("Most 'distant' reachable pairs:")
for (i, j) in late_pairs[:10]:
    print(f"  ({i+1:>2}, {j+1:>2}) — From {names[j]}  →  {names[i]}")

print()
never_pairs = [(i, j) for i in range(n) for j in range(n)
               if not np.isfinite(first_nonzero[i,j]) and i != j]
print(f"Pairs with no directed walk of any length: {len(never_pairs)}")
print("These confirm the network is not strongly connected.")

"""We are going to examine A^4, the power at which entries start becoming non-zero and then identify the largest entry."""

A4 = powers[4]

max_val_A4 = A4.max()
max_pos_A4 = np.unravel_index(A4.argmax(), A4.shape)
i4, j4 = max_pos_A4

print(f"Largest entry in A⁴: {max_val_A4}")
print(f"  Located at index: ({i4+1}, {j4+1})")
print(f"  i = {names[i4]}")
print(f"  j = {names[j4]}")
print()
print(f"Interpretation:")
print(f"  There are {max_val_A4} distinct directed walks of length 4")
print(f"  starting from '{names[j4]}' and ending at '{names[i4]}'.")
print(f"  This means these two individuals are very 'centrally connected in the network'")

print("Verification of out-degree condition for Task 4(b):")
print()
for idx, name in enumerate(names):
    out_deg = A[:, idx].sum()
    if out_deg == 0:
        print(f"  {name}: out-degree = 0  (follows NO classmates)")
        print(f"  Theorem 4(b) precondition FAILS for this node.")
print()
print("Conclusion: Since at least one node has out-degree 0,")
print("the hypothesis of 4(b) (all-positive A^m) can never be satisfied,")
print("and any A^m would retain a zero column, so A^(m+1) would too.")